# Generated by Django 6.0.6 on 2026-06-29 04:30

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='shop_code',
            field=models.CharField(blank=True, default=orders.models.generate_shop_code, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('owner', 'username')},
        ),
    ]
